# Generated by Django 4.2.7 on 2024-03-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoilDeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('Temperature', models.FloatField()),
                ('Humidity', models.FloatField()),
                ('SoilMoisture', models.FloatField()),
                ('MotorID', models.CharField(max_length=5)),
                ('MotorStatus', models.CharField(max_length=5)),
            ],
        ),
    ]
