# Generated by Django 4.2.7 on 2024-03-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soildevice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soildevicedata',
            name='MotorID',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='soildevicedata',
            name='MotorStatus',
            field=models.FloatField(),
        ),
    ]
