# Generated by Django 4.2.7 on 2024-03-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction', models.CharField(max_length=5)),
                ('rain_gauge', models.FloatField()),
                ('running_time', models.FloatField()),
                ('mag_x', models.FloatField()),
                ('mag_y', models.FloatField()),
                ('mag_z', models.FloatField()),
                ('mag_strength', models.FloatField()),
                ('acc_x', models.IntegerField()),
                ('acc_y', models.IntegerField()),
                ('acc_z', models.IntegerField()),
                ('acc_strength', models.IntegerField()),
            ],
        ),
    ]
