# Generated by Django 4.2.7 on 2024-01-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('Pressure', models.FloatField()),
                ('LightLevel', models.FloatField()),
                ('SoilMoisture', models.FloatField()),
                ('SoilTemp', models.FloatField()),
                ('WindSpeed', models.FloatField()),
                ('WindDirection', models.CharField(max_length=50, verbose_name='')),
                ('RainGuage', models.FloatField()),
                ('Altitude', models.FloatField()),
            ],
        ),
    ]
