# Generated by Django 4.2.7 on 2024-01-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherstation', '0002_alter_weatherdata_winddirection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='WindDirection',
            field=models.CharField(max_length=5),
        ),
    ]
