# Generated by Django 4.2.7 on 2024-03-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agvRoverData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('pitch', models.FloatField()),
                ('roll', models.FloatField()),
                ('yaw', models.FloatField()),
            ],
        ),
    ]
